
spring:
  application:
    name: kookdonge
  datasource:
    url: jdbc:mysql://localhost:3306/kookdonge_local
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    open-in-view: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
  sql:
    init:
      mode: never
  cors:
    allowed-origins: "*"

logging:
  level:
    com.kookdonge.kookdonge_server: DEBUG


auth:
  jwt:
    secret-key: "kookdonge-super-secret-key-for-jwt-token-generation-with-256-bits-length-minimum-requirement"

google:
  client:
    id: asdf
    secret: asdf
    redirect-uri: http://localhost:8080/oauth2/callback/google