
spring:
  application:
    name: kookdonge
  datasource:
    url: jdbc:mysql://localhost:3306/kookdonge_local
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    open-in-view: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
  sql:
    init:
      mode: never
  cors:
    allowed-origins: "*"
  mail:
    host: smtp.gmail.com
    port: 587
    username: kookdonge@gmail.com
    password: qwe
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connection timeout: 5000
          timeout: 5000
          write timeout: 5000

logging:
  level:
    com.kookdonge.kookdonge_server: DEBUG


auth:
  jwt:
    secret-key: "kookdonge-super-secret-key-for-jwt-token-generation-with-256-bits-length-minimum-requirement"

google:
  client:
    id: 1068916533247-f3trlv7kmrfdr911nrbm4o8d2vlmnovh.apps.googleusercontent.com
    secret: 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
    redirect-uri: http://localhost:3000/register/register-info

cloud:
    aws:
      s3:
        bucket: ${AWS_S3_BUCKET:kookdonge-bucket}
      region: ap-northeast-2
      credentials:
        accessKey: ${AWS_ACCESS_KEY:a}
        secretKey: ${AWS_SECRET_KEY:b}